import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/l10n/app_localizations.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/utils/responsive.dart';
import '../../domain/providers/auth_provider.dart';
import '../../domain/models/auth_models.dart';

class RegisterScreen extends ConsumerStatefulWidget {
  const RegisterScreen({super.key});

  @override
  ConsumerState<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends ConsumerState<RegisterScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();
  final _confirmPasswordController = TextEditingController();
  String _selectedRole = 'customer';
  String? _selectedPropertyType;
  bool _obscurePassword = true;
  bool _obscureConfirmPassword = true;
  
  // Username validation state
  bool _usernameChecking = false;
  bool? _usernameAvailable;
  Timer? _usernameDebounce;
  bool _usernameAutoGenerated = false;

  static const List<Map<String, String>> _propertyTypes = [
    {'key': 'personal_residential', 'icon': 'home'},
    {'key': 'residential_compounds', 'icon': 'apartment'},
    {'key': 'offices', 'icon': 'business'},
    {'key': 'banks', 'icon': 'account_balance'},
    {'key': 'government_buildings', 'icon': 'domain'},
    {'key': 'schools_universities', 'icon': 'school'},
    {'key': 'hospitals_clinics', 'icon': 'local_hospital'},
    {'key': 'hotels', 'icon': 'hotel'},
    {'key': 'retail_shops', 'icon': 'store'},
    {'key': 'factories_warehouses', 'icon': 'factory'},
    {'key': 'restaurants_cafes', 'icon': 'restaurant'},
    {'key': 'community_centers', 'icon': 'groups'},
    {'key': 'religious_buildings', 'icon': 'mosque'},
    {'key': 'car_owners_garages', 'icon': 'directions_car'},
  ];

  @override
  void initState() {
    super.initState();
    _nameController.addListener(_onNameChanged);
    _usernameController.addListener(_onUsernameChanged);
  }

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _usernameController.dispose();
    _passwordController.dispose();
    _confirmPasswordController.dispose();
    _usernameDebounce?.cancel();
    super.dispose();
  }

  void _onNameChanged() {
    // Auto-generate username when name changes (if username was auto-generated or empty)
    if (_usernameAutoGenerated || _usernameController.text.isEmpty) {
      _generateUsername();
    }
  }

  void _onUsernameChanged() {
    // Mark as manually edited if user types something different
    if (!_usernameAutoGenerated) {
      _checkUsernameAvailability(_usernameController.text);
    }
  }

  Future<void> _generateUsername() async {
    final name = _nameController.text.trim();
    if (name.isEmpty) return;

    final repo = ref.read(authRepositoryProvider);
    final result = await repo.generateUsername(name);
    if (result.isSuccess && mounted) {
      final username = result.data!['username'] as String;
      setState(() {
        _usernameController.text = username;
        _usernameAutoGenerated = true;
        _usernameAvailable = true;
        _usernameChecking = false;
      });
    }
  }

  void _checkUsernameAvailability(String username) {
    _usernameDebounce?.cancel();
    if (username.length < 3) {
      setState(() {
        _usernameAvailable = null;
        _usernameChecking = false;
      });
      return;
    }

    setState(() => _usernameChecking = true);

    _usernameDebounce = Timer(const Duration(milliseconds: 500), () async {
      final repo = ref.read(authRepositoryProvider);
      final result = await repo.checkUsername(username);
      if (mounted) {
        setState(() {
          _usernameChecking = false;
          if (result.isSuccess) {
            _usernameAvailable = result.data!['available'] == true;
          } else {
            _usernameAvailable = null;
          }
        });
      }
    });
  }

  Future<void> _handleRegister() async {
    if (!_formKey.currentState!.validate()) return;
    if (_usernameAvailable == false) return;

    await ref.read(authStateProvider.notifier).register(
          fullName: _nameController.text.trim(),
          email: _emailController.text.trim(),
          phone: _phoneController.text.trim(),
          password: _passwordController.text,
          role: _selectedRole,
          username: _usernameController.text.trim(),
        );
  }

  Widget _buildUsernameField(AppLocalizations l10n) {
    Color? suffixColor;
    IconData? suffixIcon;
    String? suffixText;

    if (_usernameChecking) {
      // Show loading indicator
    } else if (_usernameAvailable == true) {
      suffixColor = Colors.green;
      suffixIcon = Icons.check_circle;
      suffixText = l10n.translate('available');
    } else if (_usernameAvailable == false) {
      suffixColor = Colors.red;
      suffixIcon = Icons.cancel;
      suffixText = l10n.translate('not_available');
    }

    return TextFormField(
      controller: _usernameController,
      decoration: InputDecoration(
        labelText: l10n.translate('username'),
        prefixIcon: const Icon(Icons.alternate_email),
        suffixIcon: _usernameChecking
            ? const Padding(
                padding: EdgeInsets.all(12),
                child: SizedBox(
                  height: 20,
                  width: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              )
            : suffixIcon != null
                ? Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(suffixIcon, color: suffixColor, size: 20),
                      const SizedBox(width: 4),
                      Text(
                        suffixText ?? '',
                        style: TextStyle(color: suffixColor, fontSize: 12),
                      ),
                      const SizedBox(width: 8),
                    ],
                  )
                : null,
        helperText: l10n.translate('username_hint'),
        enabledBorder: _usernameAvailable == false
            ? OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Colors.red),
              )
            : _usernameAvailable == true
                ? OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: const BorderSide(color: Colors.green),
                  )
                : null,
        focusedBorder: _usernameAvailable == false
            ? OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Colors.red, width: 2),
              )
            : _usernameAvailable == true
                ? OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: const BorderSide(color: Colors.green, width: 2),
                  )
                : null,
      ),
      onChanged: (value) {
        _usernameAutoGenerated = false;
        _checkUsernameAvailability(value);
      },
      validator: (v) {
        if (v == null || v.isEmpty) return l10n.translate('username_required');
        if (v.length < 3) return l10n.translate('username_too_short');
        if (_usernameAvailable == false) return l10n.translate('username_taken');
        return null;
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final authState = ref.watch(authStateProvider);

    ref.listen<AuthState>(authStateProvider, (prev, next) {
      if (next.error != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(next.error!), backgroundColor: AppTheme.errorColor),
        );
      }
    });

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.go('/login'),
        ),
        title: Text(l10n.register),
      ),
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: Responsive.pagePadding(context),
            child: ResponsiveCenter(
              maxWidth: Responsive.maxFormWidth(context),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Text(
                      l10n.selectRole,
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(
                          child: _RoleCard(
                            icon: Icons.person_rounded,
                            label: l10n.customer,
                            isSelected: _selectedRole == 'customer',
                            onTap: () => setState(() => _selectedRole = 'customer'),
                          ),
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: _RoleCard(
                            icon: Icons.engineering_rounded,
                            label: l10n.technician,
                            isSelected: _selectedRole == 'technician',
                            onTap: () => setState(() => _selectedRole = 'technician'),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),
                    // Property type dropdown for customers
                    if (_selectedRole == 'customer') ...[
                      Text(
                        l10n.propertyType,
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                      const SizedBox(height: 8),
                      DropdownButtonFormField<String>(
                        initialValue: _selectedPropertyType,
                        decoration: InputDecoration(
                          prefixIcon: const Icon(Icons.home_work_outlined),
                          labelText: l10n.selectPropertyType,
                        ),
                        items: _propertyTypes.map((pt) {
                          return DropdownMenuItem(
                            value: pt['key'],
                            child: Text(l10n.translate(pt['key']!)),
                          );
                        }).toList(),
                        onChanged: (v) => setState(() => _selectedPropertyType = v),
                      ),
                      const SizedBox(height: 16),
                    ],
                    TextFormField(
                      controller: _nameController,
                      textCapitalization: TextCapitalization.words,
                      decoration: InputDecoration(
                        labelText: l10n.fullName,
                        prefixIcon: const Icon(Icons.person_outlined),
                      ),
                      validator: (v) =>
                          v == null || v.isEmpty ? 'Name is required' : null,
                    ),
                    const SizedBox(height: 16),
                    _buildUsernameField(l10n),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _emailController,
                      keyboardType: TextInputType.emailAddress,
                      decoration: InputDecoration(
                        labelText: l10n.email,
                        prefixIcon: const Icon(Icons.email_outlined),
                      ),
                      validator: (v) {
                        if (v == null || v.isEmpty) return 'Email is required';
                        if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$')
                            .hasMatch(v)) {
                          return 'Enter a valid email';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _phoneController,
                      keyboardType: TextInputType.phone,
                      decoration: InputDecoration(
                        labelText: l10n.phone,
                        prefixIcon: const Icon(Icons.phone_outlined),
                      ),
                      validator: (v) =>
                          v == null || v.isEmpty ? 'Phone is required' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _passwordController,
                      obscureText: _obscurePassword,
                      decoration: InputDecoration(
                        labelText: l10n.password,
                        prefixIcon: const Icon(Icons.lock_outlined),
                        suffixIcon: IconButton(
                          icon: Icon(_obscurePassword
                              ? Icons.visibility_off_outlined
                              : Icons.visibility_outlined),
                          onPressed: () =>
                              setState(() => _obscurePassword = !_obscurePassword),
                        ),
                      ),
                      validator: (v) {
                        if (v == null || v.isEmpty) return 'Password is required';
                        if (v.length < 8) return 'At least 8 characters';
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _confirmPasswordController,
                      obscureText: _obscureConfirmPassword,
                      decoration: InputDecoration(
                        labelText: 'Confirm Password',
                        prefixIcon: const Icon(Icons.lock_outlined),
                        suffixIcon: IconButton(
                          icon: Icon(_obscureConfirmPassword
                              ? Icons.visibility_off_outlined
                              : Icons.visibility_outlined),
                          onPressed: () => setState(
                              () => _obscureConfirmPassword = !_obscureConfirmPassword),
                        ),
                      ),
                      validator: (v) {
                        if (v != _passwordController.text) {
                          return 'Passwords do not match';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 32),
                    ElevatedButton(
                      onPressed: authState.isLoading ? null : _handleRegister,
                      child: authState.isLoading
                          ? const SizedBox(
                              height: 24,
                              width: 24,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                          : Text(l10n.register),
                    ),
                    const SizedBox(height: 16),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(l10n.alreadyHaveAccount),
                        TextButton(
                          onPressed: () => context.go('/login'),
                          child: Text(l10n.login),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class _RoleCard extends StatelessWidget {
  final IconData icon;
  final String label;
  final bool isSelected;
  final VoidCallback onTap;

  const _RoleCard({
    required this.icon,
    required this.label,
    required this.isSelected,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 20),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? AppTheme.primaryColor : Colors.grey[300]!,
            width: isSelected ? 2 : 1,
          ),
          color: isSelected ? AppTheme.primaryColor.withValues(alpha: 0.05) : null,
        ),
        child: Column(
          children: [
            Icon(icon,
                size: 36,
                color: isSelected ? AppTheme.primaryColor : Colors.grey),
            const SizedBox(height: 8),
            Text(
              label,
              style: TextStyle(
                fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                color: isSelected ? AppTheme.primaryColor : Colors.grey[700],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
